global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "application-metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
    
      # For localhost: "host.docker.internal:3050"
      - targets: ["recipe-manager-mp1-e0406370-production.up.railway.app:443"]
    scheme: "https"
